@startuml 演習6-3-2

[*] -right-> メニュー画面
メニュー画面 --> 予約と確認画面
予約と確認画面 --> メニュー画面 


予約と確認画面 --right--> あなたの順番
予約と確認画面 --right--> あなたの順番

あなたの順番 -down-> メニュー画面

メニュー画面 -down-> 今の順番
今の順番 -down-> メニュー画面
メニュー画面 -right->[*]