@startuml ユースケース図
left to right direction
actor 利用者 #AA8c00;line:DarkKhaki;line.bold;
actor 従業員 #BB8c00;line:DarkTurquoise;line.bold;
actor 管理者 #ff8c00;line:DarkGoldenRod;line.bold;
rectangle ホテル予約システム{
usecase 空室状況を閲覧
usecase (<u>部屋を予約<u> \n extention points \n キャンペーン期間) as input
usecase 空室状況を入力
usecase 予約の集計
usecase 会員登録
usecase ログイン
usecase キャンペーン価格にする
}
キャンペーン価格にする .> input: <<extend>>
利用者 ---> input
利用者 ---> 空室状況を閲覧
空室状況を閲覧 ..> ログイン: <<include>>
従業員 --> 空室状況を入力
空室状況を入力 ..> ログイン: <<include>>
ログイン ..> 会員登録: <<include>>
管理者 -> 予約の集計
予約の集計 ..> ログイン: <<include>>
会員登録 ..> input: <<include>>
管理者 ---|> 従業員
@enduml