@startuml カレーライス
title カレーライスの作り方🍛
start
:材料を用意する
六人前
豚バラブロック 190g
人参           1本
玉ねぎ         1個
じゃがいも     1個
カレールー     115g
水            830ml
サラダ油       適量;

:事前準備
じゃがいもは皮を向き、芽を取り除いておきます。
その他の野菜も皮をむいておきます。;
    fork
        :肉と野菜を一口大に切ります;
        :フライパンにサラダ油を引いたら中火で肉を炒めます。;
        :野菜を加え、玉ねぎが透き通るくらいまで炒めます。;
        :水を加えて１５～２０分煮込みます。;
    fork again
        :お米を洗う;
        :ご飯を炊く;
    end fork 
:🍛カレールーを加えて完全に溶かしながら１０分煮込んで完成;
stop
@enduml
