@startuml 演習3-5
    left to right direction
    object "<u>ホテルリスト:ホテルUML</u>" as hotel{
        部屋
    }

    object "<u>客室リスト:客室</u>" as room1{
        部屋番号=301
        タイプ=シングル
        価格=11000円
        キャンペーン価格=9000円
    }

    object "<u>客室リスト:客室</u>" as room2{
        部屋番号=302
        タイプ=シングル
        価格=11000円
        キャンペーン価格=9000円
    }
    
    object "<u>客室リスト:客室</u>" as room3{
        部屋番号=303
        タイプ=シングル
        価格=11000円
        キャンペーン価格=9000円
    }

    object "<u>予約リスト:予約" as reservation{
        チェックイン日=5月3日
        滞在期間=2泊
        値段
    }

    object "<u>利用者情報:利用者</u>" as user1{
        氏名=Aさん
        住所
        電話番号
    }

    object "<u>利用者情報:利用者</u>" as user2{
        氏名=Bさん
        住所
        電話番号
    }

    hotel -up- room1
    hotel -up- room2
    hotel -up- room3
    reservation -- room1
    reservation -- room2
    reservation -- room3
    reservation -left- user1
    reservation -left- user2
@enduml