@startuml
' left to right direction
class "空車リスト" as empty_car {
- 日付 : Date
}
class "車" as car {
- 識別管理番号:int
- 車種:String
- 駆動方式:String
}
class "貸出" as rental {
- 貸出番号:int
- 貸出日:int
}
class "顧客" as customer {
- 顧客ID: String
- 名前: String
- 電話番号:String
- 郵便番号:String
- 住所:String
---
setName(氏名:string) void
}
class "予約" as reserve {
- 予約番号: int
- 予約日:Date
}
@enduml